### ISSUE TITLE
option to detect *either* positive or negative spikes

### ISSUE THREAD

**Issue by nsteinme** [klusta-team/spikedetekt2#24]
Both can happen, so if you think both are in your dataset, then you should be able to detect either way. I'm not sure if this is anything more complicated than taking the abs of the signal and then using the positive mode?

**Comment by rossant** [comment]
https://github.com/klusta-team/spikedetekt2/blob/master/spikedetekt2/core/main.py#L33 ?

**Comment by nsteinme** [comment]
Ok!
